
services:
  backend_rds:
    build:
      context: ./backend_rds  # вказуємо папку, де знаходиться Dockerfile
      dockerfile: Dockerfile  # Dockerfile знаходиться в цій папці
    environment:
      NAME: ${DB_USER}
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}      
      HOST: ${DB_HOST},
      PORT: ${DB_PORT},
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - backend

  backend_redis:
    build:
      context: ./backend_redis  # вказуємо папку, де знаходиться Dockerfile
      dockerfile: Dockerfile  # Dockerfile знаходиться в цій папці
    ports:
      - "8002:8002"
    depends_on:
      - redis
    networks:
      - backend

  frontend:
    image: 339712948510.dkr.ecr.eu-north-1.amazonaws.com/tickera/rds:latest
    ports:
      - "8000:8000"
    depends_on:
      - backend_rds
      - backend_redis
    networks:
      - frontend_network

  
